title: CircuitPython
email: justin@adafruit.com
description: >-
  The easiest way to program microcontrollers
site_image: "https://circuitpython.org/assets/images/CircuitPythonLogo_Black.png"
timezone: America/New_York
twitter_username: circuitpython
github_username: adafruit
baseurl: ""
url: "https://circuitpython.org"
paginate: 5
excerpt_separator: <!--more-->
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-get-json
  - jekyll-redirect-from
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
style: :compressed

# Collections
collections:
  board:
    output: true
  blinka:
    output: true

jekyll_get_json:
  - data: libraries
    json: "https://adafruit-circuit-python.s3.amazonaws.com/adabot/web/libraries.v2.json"
  - data: guides
    json: "https://learn.adafruit.com/api/categories/circuitpython.json?count=50&filter=guides_only,random,exclude_product"

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - template.md
  - Rakefile
  - .idea
  - assets/images/boards/original
